// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjREBhNxc7XqAqdH8mMNn1Qq-WNenI_F8',
    appId: '1:486717687749:web:b22d977c1f37a66aa52dac',
    messagingSenderId: '486717687749',
    projectId: 'winetopia-app',
    authDomain: 'winetopia-app.firebaseapp.com',
    storageBucket: 'winetopia-app.appspot.com',
    measurementId: 'G-XGM1DFZRLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbsjqm6b24QxOMd-qvTCwwAKDE9Rl8EAY',
    appId: '1:486717687749:android:557627b7e5d0d39aa52dac',
    messagingSenderId: '486717687749',
    projectId: 'winetopia-app',
    storageBucket: 'winetopia-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjAPTxaw-OMb6GLRIcl9Cjpsf0158xVKg',
    appId: '1:486717687749:ios:42163167167a20dda52dac',
    messagingSenderId: '486717687749',
    projectId: 'winetopia-app',
    storageBucket: 'winetopia-app.appspot.com',
    iosBundleId: 'com.example.winetopia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjAPTxaw-OMb6GLRIcl9Cjpsf0158xVKg',
    appId: '1:486717687749:ios:42163167167a20dda52dac',
    messagingSenderId: '486717687749',
    projectId: 'winetopia-app',
    storageBucket: 'winetopia-app.appspot.com',
    iosBundleId: 'com.example.winetopia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjREBhNxc7XqAqdH8mMNn1Qq-WNenI_F8',
    appId: '1:486717687749:web:70abdbd7ee6997e3a52dac',
    messagingSenderId: '486717687749',
    projectId: 'winetopia-app',
    authDomain: 'winetopia-app.firebaseapp.com',
    storageBucket: 'winetopia-app.appspot.com',
    measurementId: 'G-ZVJ2XQXHHC',
  );
}
